// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppBindings exposes methods to the frontend via Wails bindings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * AddShortcut adds a single shortcut
 * @param {string} trigger
 * @param {string} replacement
 * @returns {$CancellablePromise<void>}
 */
export function AddShortcut(trigger, replacement) {
    return $Call.ByID(1733001600, trigger, replacement);
}

/**
 * CheckForUpdates checks GitHub for a newer version
 * @param {boolean} force
 * @returns {$CancellablePromise<services$0.UpdateInfo | null>}
 */
export function CheckForUpdates(force) {
    return $Call.ByID(152619814, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DetectCurrentApp returns the process name of the currently focused application
 * User can click "Detect" button, switch to target app, and the name will be captured
 * @returns {$CancellablePromise<string>}
 */
export function DetectCurrentApp() {
    return $Call.ByID(3058819472);
}

/**
 * DownloadAndInstallUpdate downloads and installs the update
 * @param {string} downloadURL
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAndInstallUpdate(downloadURL) {
    return $Call.ByID(29466370, downloadURL);
}

/**
 * GetEnabled returns whether Vietnamese input is enabled
 * @returns {$CancellablePromise<boolean>}
 */
export function GetEnabled() {
    return $Call.ByID(4139715286);
}

/**
 * GetFormattingConfig returns the formatting configuration
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetFormattingConfig() {
    return $Call.ByID(2794236240).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetInputMethod returns current input method (0=Telex, 1=VNI)
 * @returns {$CancellablePromise<number>}
 */
export function GetInputMethod() {
    return $Call.ByID(4128310114);
}

/**
 * GetSettings returns all settings
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSettings() {
    return $Call.ByID(3726452464).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetShortcuts returns all shortcuts
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetShortcuts() {
    return $Call.ByID(96855928).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetVersion returns app version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(3451983167);
}

/**
 * OpenReleasePage opens the release page in browser
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenReleasePage(url) {
    return $Call.ByID(2902927167, url);
}

/**
 * RemoveShortcut removes a shortcut
 * @param {string} trigger
 * @returns {$CancellablePromise<void>}
 */
export function RemoveShortcut(trigger) {
    return $Call.ByID(2479821437, trigger);
}

/**
 * SaveFormattingConfig saves the formatting configuration
 * @param {{ [_: string]: any }} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveFormattingConfig(config) {
    return $Call.ByID(4109063599, config);
}

/**
 * SaveSettings saves all settings
 * @param {{ [_: string]: any }} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1235119979, settings);
}

/**
 * SaveShortcuts saves all shortcuts
 * @param {{ [_: string]: any }[]} shortcuts
 * @returns {$CancellablePromise<void>}
 */
export function SaveShortcuts(shortcuts) {
    return $Call.ByID(2491486897, shortcuts);
}

/**
 * SetEnabled toggles Vietnamese input on/off
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(enabled) {
    return $Call.ByID(1538332202, enabled);
}

/**
 * SetInputMethod sets input method
 * @param {number} method
 * @returns {$CancellablePromise<void>}
 */
export function SetInputMethod(method) {
    return $Call.ByID(526728894, method);
}

/**
 * Toggle toggles IME and returns new state
 * @returns {$CancellablePromise<boolean>}
 */
export function Toggle() {
    return $Call.ByID(4113297479);
}

// Private type creation functions
const $$createType0 = services$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
