// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppBindings exposes methods to the frontend via Wails bindings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AddShortcut adds a single shortcut
 * @param {string} trigger
 * @param {string} replacement
 * @returns {$CancellablePromise<void>}
 */
export function AddShortcut(trigger, replacement) {
    return $Call.ByID(1733001600, trigger, replacement);
}

/**
 * GetEnabled returns whether Vietnamese input is enabled
 * @returns {$CancellablePromise<boolean>}
 */
export function GetEnabled() {
    return $Call.ByID(4139715286);
}

/**
 * GetInputMethod returns current input method (0=Telex, 1=VNI)
 * @returns {$CancellablePromise<number>}
 */
export function GetInputMethod() {
    return $Call.ByID(4128310114);
}

/**
 * GetSettings returns all settings
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetSettings() {
    return $Call.ByID(3726452464).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetShortcuts returns all shortcuts
 * @returns {$CancellablePromise<{ [_: string]: string }[]>}
 */
export function GetShortcuts() {
    return $Call.ByID(96855928).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetVersion returns app version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(3451983167);
}

/**
 * RemoveShortcut removes a shortcut
 * @param {string} trigger
 * @returns {$CancellablePromise<void>}
 */
export function RemoveShortcut(trigger) {
    return $Call.ByID(2479821437, trigger);
}

/**
 * SaveSettings saves all settings
 * @param {{ [_: string]: any }} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1235119979, settings);
}

/**
 * SaveShortcuts saves all shortcuts
 * @param {{ [_: string]: string }[]} shortcuts
 * @returns {$CancellablePromise<void>}
 */
export function SaveShortcuts(shortcuts) {
    return $Call.ByID(2491486897, shortcuts);
}

/**
 * SetEnabled toggles Vietnamese input on/off
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(enabled) {
    return $Call.ByID(1538332202, enabled);
}

/**
 * SetInputMethod sets input method
 * @param {number} method
 * @returns {$CancellablePromise<void>}
 */
export function SetInputMethod(method) {
    return $Call.ByID(526728894, method);
}

/**
 * Toggle toggles IME and returns new state
 * @returns {$CancellablePromise<boolean>}
 */
export function Toggle() {
    return $Call.ByID(4113297479);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($$createType1);
