name: 🐛 Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - Windows 11
        - Windows 10
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: GoNhanh version
      placeholder: "1.0.0"
